---
- name: apache webserver installation
  hosts: all
  remote_user: ansible
  become: true

  tasks:
  - name: apache installation
    ansible.builtin.apt:
      name: apache2
      state: present
  - name: start apache2 service
    ansible.builtin.service:
      name: apache2
      state: started